import blog from "../../assets/images/sands.png";
import cement from "../../assets/images/cements.png";
import steel from "../../assets/images/steels.png";
import stones from "../../assets/images/granites.png";



export const products = [
    {
        id: "1",
        img: blog,
        tittle: "20 Tons of Sharp Filling Sand ",
        price: "NGN 80,800",
        rating: 4,
        category: "Sand",
    },
    {
        id: "2",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 3.5,
        category: "Cement",
    },
    {
        id: "3",
        img: stones,
        tittle: "10 Tons Construction Stones",
        price: "NGN 190,000",
        rating: 3,
        category: "Gravel",
    },
    {
        id: "4",
        img: steel,
        tittle: "Steel Reinforcement (Local) ",
        price: "NGN 458,800",
        rating: 4,
        category: "Steel",
    },
    {
        id: "5",
        img: stones,
        tittle: "10 Tons Construction Stones",
        price: "NGN 190,000",
        rating: 4,
        category: "Gravel",
    },
    {
        id: "6",
        img: blog,
        tittle: "20 Tons of Sharp Filling Sand ",
        price: "NGN 80,800",
        rating: 4,
        category: "Sand",
    },
    {
        id: "7",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 5,
        category: "Cement",
    },
    {
        id: "8",
        img: steel,
        tittle: "Steel Reinforcement (Local) ",
        price: "NGN 458,800",
        rating: 4,
        category: "Steel",
    },
    {
        id: "9",
        img: stones,
        tittle: "10 Tons Construction Stones",
        price: "NGN 190,000",
        rating: 5,
        category: "Gravel",
    },
    {
        id: "10",
        img: blog,
        tittle: "20 Tons of Sharp Filling Sand ",
        price: "NGN 80,800",
        rating: 4,
        category: "Sand",
    },
    {
        id: "11",
        img: blog,
        tittle: "10 Tons of Sharp Filling Sand ",
        price: "NGN 40,800",
        rating: 3,
        category: "Sand",
    },
    {
        id: "12",
        img: blog,
        tittle: "30 Tons of Sharp Filling Sand ",
        price: "NGN 130,100",
        rating: 5,
        category: "Sand",
    },
    {
        id: "13",
        img: blog,
        tittle: "5 Tons of Sharp Filling Sand ",
        price: "NGN 23,500",
        rating: 4,
        category: "Sand",
    },
    {
        id: "14",
        img: steel,
        tittle: "Steel Reinforcement (Local) ",
        price: "NGN 458,800",
        rating: 3,
        category: "Steel",
    },
    {
        id: "15",
        img: steel,
        tittle: "Steel Reinforcement ",
        price: "NGN 358,800",
        rating: 4,
        category: "Steel",
    },
    {
        id: "16",
        img: steel,
        tittle: "Steel Reinforcement (Local) ",
        price: "NGN 458,800",
        rating: 4,
        category: "Steel",
    },
    {
        id: "17",
        img: steel,
        tittle: "Steel Reinforcement (Local) ",
        price: "NGN 458,800",
        rating: 4,
        category: "Steel",
    },
    {
        id: "18",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 5,
        category: "Cement",
    },
    {
        id: "19",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 5,
        category: "Cement",
    },
    {
        id: "20",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 5,
        category: "Cement",
    },
    {
        id: "21",
        img: cement,
        tittle: "Dangote Cement Trailer Load ",
        price: "NGN 764,200",
        rating: 5,
        category: "Cement",
    },
]